# Generated by Django 5.2.1 on 2025-05-19 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_eliminar_tablas_huerfanas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildeusuario',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfildeusuario',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grupo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_set', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='RelacionAcudienteEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acudidos_asociados', to='core.perfildeusuario')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acudientes_asociados', to='core.perfildeusuario')),
            ],
            options={
                'unique_together': {('acudiente', 'estudiante')},
            },
        ),
        migrations.AddField(
            model_name='perfildeusuario',
            name='acudidos',
            field=models.ManyToManyField(blank=True, related_name='acudientes', through='core.RelacionAcudienteEstudiante', through_fields=('acudiente', 'estudiante'), to='core.perfildeusuario'),
        ),
    ]
