# Generated by Django 5.2.1 on 2025-05-23 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfildeusuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_iso', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pais'),
        ),
    ]
