# Generated by Django 5.2.1 on 2025-05-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pais_usuario_numero_documento_usuario_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.pais'),
            preserve_default=False,
        ),
    ]
