# Generated by Django 5.2.1 on 2025-05-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_departamento_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfildeusuario',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='perfildeusuario',
            name='tipo_documento',
        ),
    ]
