# Generated by Django 5.0 on 2025-05-26 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_perfildeusuario_numero_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HojaDeVidaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=30)),
                ('pais_residencia', models.CharField(max_length=50)),
                ('departamento_residencia', models.CharField(max_length=50)),
                ('municipio_residencia', models.CharField(max_length=50)),
                ('direccion_linea1', models.CharField(max_length=255)),
                ('direccion_linea2', models.CharField(blank=True, max_length=255, null=True)),
                ('estrato', models.CharField(max_length=20)),
                ('telefono_celular', models.CharField(max_length=20)),
                ('telefono_celular_alterno', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_fijo_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('correo_alterno', models.EmailField(blank=True, max_length=254, null=True)),
                ('resumen', models.TextField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoja_de_vida', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField()),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='experiencias/')),
                ('hoja_de_vida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hojadevidadocente')),
            ],
        ),
        migrations.CreateModel(
            name='EducacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50)),
                ('institucion', models.CharField(max_length=100)),
                ('titulo_obtenido', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hoja_de_vida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hojadevidadocente')),
            ],
        ),
        migrations.CreateModel(
            name='CapacitacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('duracion_horas', models.IntegerField()),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='capacitaciones/')),
                ('hoja_de_vida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hojadevidadocente')),
            ],
        ),
        migrations.CreateModel(
            name='IdiomaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=50)),
                ('nivel_habla', models.CharField(max_length=20)),
                ('nivel_lee', models.CharField(max_length=20)),
                ('nivel_escribe', models.CharField(max_length=20)),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='idiomas/')),
                ('hoja_de_vida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hojadevidadocente')),
            ],
        ),
    ]
