# Generated by Django 5.0 on 2025-05-27 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_estadocivil_estrato_genero_hojadevidadocente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojadevidadocente',
            name='departamento_residencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departamento'),
        ),
        migrations.AlterField(
            model_name='hojadevidadocente',
            name='estado_civil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estadocivil'),
        ),
        migrations.AlterField(
            model_name='hojadevidadocente',
            name='estrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estrato'),
        ),
        migrations.AlterField(
            model_name='hojadevidadocente',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.genero'),
        ),
        migrations.AlterField(
            model_name='hojadevidadocente',
            name='municipio_residencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad'),
        ),
        migrations.AlterField(
            model_name='hojadevidadocente',
            name='pais_residencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pais'),
        ),
    ]
