# Generated by Django 5.2.1 on 2025-05-28 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_hojadevidadocente_departamento_residencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildeusuario',
            name='municipio_identificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_por_municipio_ident', to='core.ciudad'),
        ),
    ]
