# Generated by Django 5.2.1 on 2025-06-09 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_perfildeusuario_municipio_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que autorizó o activó esta cuenta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_activados', to=settings.AUTH_USER_MODEL),
        ),
    ]
