# Generated by Django 5.2.1 on 2025-06-10 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfildeusuario',
            name='municipio_identificacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='activado_por',
        ),
        migrations.AddField(
            model_name='usuario',
            name='municipio_identificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_por_municipio_ident', to='core.ciudad'),
        ),
    ]
