# Generated by Django 5.2.1 on 2025-06-10 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_perfildeusuario_municipio_identificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_activados', to=settings.AUTH_USER_MODEL, verbose_name='Activado por'),
        ),
    ]
